# ============================================================================
# Risk Management Configuration
# ============================================================================
# Purpose: Define risk limits, calculation methods, and stress test scenarios
#
# Usage:
#   from modules.risk import VaRCalculator
#   import yaml
#
#   with open('config/risk_config.yaml') as f:
#       config = yaml.safe_load(f)
#
#   calculator = VaRCalculator(
#       method=config['var_methods'][0],
#       confidence_level=config['confidence_levels'][0]
#   )
#
# Author: Quant Platform Development Team
# Last Updated: 2025-10-21
# Version: 1.0.0
# ============================================================================

# ============================================================================
# Risk Limits (리스크 한도)
# ============================================================================
risk_limits:
  # VaR limits (VaR 한도)
  portfolio_var_95: 0.05          # 포트폴리오 VaR (95%) 최대 5%
  portfolio_var_99: 0.08          # 포트폴리오 VaR (99%) 최대 8%
  position_var_95: 0.01           # 개별 포지션 VaR (95%) 최대 1%

  # CVaR limits (CVaR 한도)
  portfolio_cvar_95: 0.07         # 포트폴리오 CVaR (95%) 최대 7%
  portfolio_cvar_99: 0.10         # 포트폴리오 CVaR (99%) 최대 10%

  # Volatility limits (변동성 한도)
  max_portfolio_volatility: 0.20  # 연간 최대 변동성 20%
  max_position_volatility: 0.40   # 개별 포지션 최대 변동성 40%

  # Concentration limits (집중도 한도)
  max_sector: 0.40                # 섹터 최대 40%
  max_region: 0.50                # 지역 최대 50%
  max_single_position: 0.15       # 개별 종목 최대 15%

  # Beta limits (베타 한도)
  min_beta: 0.8                   # 최소 베타 0.8 (defensive lower bound)
  max_beta: 1.2                   # 최대 베타 1.2 (aggressive upper bound)
  target_beta: 1.0                # 목표 베타 1.0 (market neutral)

  # Correlation limits (상관관계 한도)
  max_correlation_concentration: 0.7  # 최대 상관관계 0.7 (diversification)

  # Drawdown limits (낙폭 한도)
  max_drawdown: 0.20              # 최대 낙폭 20%
  max_consecutive_losses: 3       # 최대 연속 손실 3회

# ============================================================================
# VaR Calculation Methods (VaR 계산 방법)
# ============================================================================
var_methods:
  # Available methods (사용 가능한 방법)
  available:
    - historical                  # Historical simulation (역사적 시뮬레이션)
    - parametric                  # Parametric VaR (Gaussian assumption)
    - monte_carlo                 # Monte Carlo simulation

  # Default method (기본 방법)
  default: historical

  # Method-specific settings (방법별 설정)
  historical:
    lookback_days: 252            # 1년 히스토리컬 데이터
    weighted: false               # 가중치 적용 여부
    decay_factor: 0.94            # EWMA decay factor (if weighted)

  parametric:
    distribution: "normal"        # normal, t-distribution, skewed-t
    df: 5                         # degrees of freedom (t-distribution)

  monte_carlo:
    n_simulations: 10000          # 시뮬레이션 횟수
    random_seed: 42               # 재현성을 위한 시드
    correlation_method: "pearson" # pearson, kendall, spearman

# ============================================================================
# Confidence Levels (신뢰수준)
# ============================================================================
confidence_levels:
  - 0.90    # 90% 신뢰수준
  - 0.95    # 95% 신뢰수준 (일반적)
  - 0.99    # 99% 신뢰수준 (보수적)

# Default confidence level (기본 신뢰수준)
default_confidence_level: 0.95

# ============================================================================
# Time Horizons (시간 지평)
# ============================================================================
time_horizons:
  # VaR time horizons in days (VaR 시간 지평, 일 단위)
  - 1       # 1-day VaR (trading risk)
  - 10      # 10-day VaR (regulatory, Basel)
  - 20      # 20-day VaR (monthly risk)

# Default time horizon (기본 시간 지평)
default_time_horizon: 10  # days

# ============================================================================
# Stress Test Scenarios (스트레스 테스트 시나리오)
# ============================================================================
stress_scenarios:
  # Historical crisis scenarios (역사적 위기 시나리오)
  - name: "2008_financial_crisis"
    description: "Global financial crisis (2008년 금융위기)"
    date: "2008-09-15"
    market_drop: -0.30            # 시장 30% 하락
    vol_spike: 2.5                # 변동성 2.5배 증가
    correlation_spike: 0.9        # 상관관계 0.9로 증가 (diversification breakdown)
    duration_days: 180            # 180일 지속

  - name: "2020_covid_crash"
    description: "COVID-19 pandemic crash (코로나19 급락)"
    date: "2020-03-16"
    market_drop: -0.35            # 시장 35% 하락
    vol_spike: 3.0                # 변동성 3배 증가
    correlation_spike: 0.95       # 상관관계 0.95로 증가
    duration_days: 30             # 30일 지속 (빠른 회복)

  - name: "2022_bear_market"
    description: "2022 bear market (2022년 약세장)"
    date: "2022-01-01"
    market_drop: -0.20            # 시장 20% 하락
    vol_spike: 1.5                # 변동성 1.5배 증가
    correlation_spike: 0.85       # 상관관계 0.85로 증가
    duration_days: 365            # 365일 지속 (장기 조정)

  # Hypothetical scenarios (가상 시나리오)
  - name: "hypothetical_crash"
    description: "Hypothetical severe crash (가상 극심한 급락)"
    market_drop: -0.40            # 시장 40% 하락
    vol_spike: 4.0                # 변동성 4배 증가
    correlation_spike: 1.0        # 완전 상관관계
    duration_days: 60             # 60일 지속

  - name: "sector_rotation"
    description: "Rapid sector rotation (급격한 섹터 로테이션)"
    sector_shocks:
      Technology: -0.30           # 기술주 30% 하락
      Financials: 0.15            # 금융주 15% 상승
      Healthcare: 0.10            # 헬스케어 10% 상승
      Consumer: -0.10             # 소비재 10% 하락

  - name: "interest_rate_shock"
    description: "Sudden interest rate hike (급격한 금리 인상)"
    interest_rate_change: 0.03    # 3% 금리 인상
    duration_corrective_move: -0.15  # 듀레이션 리스크로 15% 하락

# ============================================================================
# Correlation Analysis (상관관계 분석)
# ============================================================================
correlation_analysis:
  # Rolling correlation settings (롤링 상관관계 설정)
  rolling_window_days: 60         # 60일 롤링 윈도우
  update_frequency: "daily"       # daily, weekly, monthly

  # Correlation thresholds (상관관계 임계값)
  high_correlation_threshold: 0.7  # 높은 상관관계
  low_correlation_threshold: 0.3   # 낮은 상관관계

  # Diversification metrics (다변화 지표)
  calculate_diversification_ratio: true
  target_diversification_ratio: 1.5  # >1.0 indicates diversification

# ============================================================================
# Factor Exposure Tracking (팩터 노출도 추적)
# ============================================================================
factor_exposure:
  # Tracked factors (추적 팩터)
  factors:
    - momentum
    - value
    - quality
    - low_volatility
    - size

  # Exposure limits (노출도 한도)
  max_factor_exposure: 0.5        # 각 팩터 최대 0.5 노출
  min_factor_exposure: -0.5       # 각 팩터 최소 -0.5 노출

  # Rebalancing trigger (리밸런싱 트리거)
  exposure_drift_threshold: 0.2   # 0.2 이탈 시 리밸런싱

# ============================================================================
# Sector Exposure Limits (섹터 노출도 한도)
# ============================================================================
sector_exposure:
  # GICS sector limits (GICS 섹터 한도)
  limits:
    Technology: 0.40              # 기술 최대 40%
    Financials: 0.30              # 금융 최대 30%
    Healthcare: 0.30              # 헬스케어 최대 30%
    Consumer_Discretionary: 0.25  # 임의소비재 최대 25%
    Consumer_Staples: 0.25        # 필수소비재 최대 25%
    Industrials: 0.25             # 산업재 최대 25%
    Energy: 0.20                  # 에너지 최대 20%
    Materials: 0.20               # 소재 최대 20%
    Utilities: 0.15               # 유틸리티 최대 15%
    Real_Estate: 0.15             # 부동산 최대 15%
    Communication_Services: 0.25  # 통신서비스 최대 25%

  # Minimum diversification (최소 다변화)
  min_sectors: 3                  # 최소 3개 섹터에 분산

# ============================================================================
# Liquidity Risk (유동성 리스크)
# ============================================================================
liquidity_risk:
  # Trading volume requirements (거래량 요구사항)
  min_daily_volume_usd: 1000000   # 최소 일 거래량 100만 달러
  min_bid_ask_spread_bps: 50      # 최대 호가 스프레드 50bp

  # Position size vs. volume (포지션 크기 vs 거래량)
  max_position_pct_of_adv: 0.05   # 일평균 거래량의 최대 5%

  # Liquidation time horizon (청산 시간 지평)
  max_liquidation_days: 5         # 최대 5일 내 청산 가능

# ============================================================================
# Reporting and Monitoring (보고 및 모니터링)
# ============================================================================
reporting:
  # Report frequency (보고 주기)
  daily_risk_report: true
  weekly_risk_report: true
  monthly_risk_report: true

  # Alert thresholds (알림 임계값)
  alert_on_var_breach: true
  alert_on_drawdown_breach: true
  alert_on_concentration_breach: true

  # Report format (보고 형식)
  format: "pdf"                   # pdf, html, excel

# ============================================================================
# Advanced Settings (고급 설정)
# ============================================================================
advanced:
  # Tail risk measures (꼬리 리스크 측정)
  tail_risk:
    calculate_expected_shortfall: true
    calculate_extreme_value_theory: false

  # Copula-based risk (코퓰라 기반 리스크)
  copula:
    enabled: false
    copula_type: "t-copula"       # gaussian, t-copula, clayton

  # Regime switching (국면 전환)
  regime_switching:
    enabled: false
    n_regimes: 2                  # 2-regime model (bull/bear)
