#!/bin/bash
# Quick Backfill Status Check Commands
# Usage: source scripts/check_backfill_status.sh

echo "================================================================================"
echo "BACKFILL QUICK STATUS COMMANDS"
echo "================================================================================"
echo ""
echo "1️⃣  전체 상황 확인 (추천):"
echo "   ./scripts/monitor_backfills.sh"
echo ""
echo "2️⃣  실시간 자동 갱신 (10초마다):"
echo "   watch -n 10 ./scripts/monitor_backfills.sh"
echo ""
echo "3️⃣  DART 백필 진행률:"
echo "   tail -5 logs/dart_production_backfill_RESTART.log | grep -E '\[.*\]'"
echo ""
echo "4️⃣  pykrx 백필 진행률:"
echo "   tail -5 logs/pykrx_production_backfill_RESTART.log | grep -E '(Progress|Success Rate)'"
echo ""
echo "5️⃣  데이터베이스 레코드 수:"
echo "   psql -d quant_platform -c \"SELECT data_source, COUNT(*) FROM ticker_fundamentals WHERE region = 'KR' GROUP BY data_source;\""
echo ""
echo "6️⃣  프로세스 상태 확인:"
echo "   ps aux | grep 'backfill_fundamentals' | grep -v grep"
echo ""
echo "7️⃣  DART 로그 실시간 보기:"
echo "   tail -f logs/dart_production_backfill_RESTART.log"
echo ""
echo "8️⃣  pykrx 로그 실시간 보기:"
echo "   tail -f logs/pykrx_production_backfill_RESTART.log"
echo ""
echo "9️⃣  완료까지 남은 시간 추정:"
echo "   tail -20 logs/pykrx_production_backfill_RESTART.log | grep 'Remaining'"
echo ""
echo "🔟  백필 종료 (긴급시):"
echo "   ./scripts/kill_dart_backfill.sh"
echo "   pkill -f 'backfill_fundamentals_pykrx'"
echo ""
echo "================================================================================"
