#!/usr/bin/env python3
"""
Test PostgreSQL Fixtures Validation

Validates that PostgreSQL mock infrastructure works correctly:
1. Database connection and schema creation
2. Factory fixtures for tickers, fundamentals, factor scores, OHLCV
3. MockPostgresDatabaseManager interface compatibility
4. Data persistence and retrieval

Run: pytest tests/fixtures/test_postgres_fixtures.py -v
"""

import pytest
from datetime import datetime, timedelta


class TestPostgresFixtures:
    """Test PostgreSQL fixture infrastructure"""

    def test_database_connection(self, postgres_test_db):
        """Test that temporary database connects successfully"""
        assert postgres_test_db is not None
        # Database name generated by pytest-postgresql (e.g., 'tests')
        assert postgres_test_db.database is not None

        # Verify schema tables exist
        query = """
            SELECT table_name
            FROM information_schema.tables
            WHERE table_schema = 'public'
            ORDER BY table_name
        """
        result = postgres_test_db.execute_query(query, ())

        table_names = [row['table_name'] for row in result]
        assert 'tickers' in table_names
        assert 'ticker_fundamentals' in table_names
        assert 'factor_scores' in table_names
        assert 'ohlcv_data' in table_names

    def test_ticker_factory(self, ticker_factory, postgres_test_db):
        """Test ticker factory creates and retrieves tickers"""

        # Create test ticker
        ticker_data = ticker_factory(
            ticker='005930',
            name='Samsung Electronics',
            sector='Technology',
            industry='Semiconductors'
        )

        assert ticker_data['ticker'] == '005930'
        assert ticker_data['name'] == 'Samsung Electronics'
        assert ticker_data['sector'] == 'Technology'

        # Verify ticker was inserted
        query = "SELECT * FROM tickers WHERE ticker = %s AND region = %s"
        result = postgres_test_db.execute_query(query, ('005930', 'KR'))

        assert len(result) == 1
        assert result[0]['ticker'] == '005930'
        assert result[0]['name'] == 'Samsung Electronics'

    def test_fundamentals_factory_pykrx(self, fundamentals_factory, ticker_factory, postgres_test_db):
        """Test fundamentals factory with pykrx (daily) data"""

        # Create ticker first
        ticker_factory(ticker='005930')

        # Create pykrx fundamentals
        fund_data = fundamentals_factory(
            ticker='005930',
            date='2024-03-29',
            period_type='DAILY',
            data_source='pykrx',
            dividend_yield=2.5,
            per=15.0,
            pbr=1.2,
            market_cap=400000000000000
        )

        assert fund_data['ticker'] == '005930'
        assert fund_data['dividend_yield'] == 2.5
        assert fund_data['per'] == 15.0

        # Verify fundamentals were inserted
        query = """
            SELECT * FROM ticker_fundamentals
            WHERE ticker = %s AND region = %s AND period_type = %s AND data_source = %s
        """
        result = postgres_test_db.execute_query(query, ('005930', 'KR', 'DAILY', 'pykrx'))

        assert len(result) == 1
        assert float(result[0]['dividend_yield']) == 2.5
        assert float(result[0]['per']) == 15.0

    def test_fundamentals_factory_dart(self, fundamentals_factory, ticker_factory, postgres_test_db):
        """Test fundamentals factory with DART (semi-annual) data"""

        # Create ticker first
        ticker_factory(ticker='005930')

        # Create DART fundamentals
        fund_data = fundamentals_factory(
            ticker='005930',
            date='2024-03-31',
            fiscal_year=2024,
            period_type='SEMI-ANNUAL',
            data_source='DART',
            revenue=100000000000,
            ebitda=20000000000,
            total_assets=500000000000
        )

        assert fund_data['ticker'] == '005930'
        assert fund_data['revenue'] == 100000000000
        assert fund_data['ebitda'] == 20000000000

        # Verify DART fundamentals were inserted
        query = """
            SELECT * FROM ticker_fundamentals
            WHERE ticker = %s AND region = %s AND period_type = %s AND data_source = %s
        """
        result = postgres_test_db.execute_query(query, ('005930', 'KR', 'SEMI-ANNUAL', 'DART'))

        assert len(result) == 1
        assert float(result[0]['revenue']) == 100000000000
        assert float(result[0]['ebitda']) == 20000000000

    def test_factor_score_factory(self, factor_score_factory, ticker_factory, postgres_test_db):
        """Test factor score factory creates and retrieves scores"""

        # Create ticker first
        ticker_factory(ticker='005930')

        # Create factor score
        score_data = factor_score_factory(
            ticker='005930',
            factor_name='Dividend_Yield',
            date='2024-03-29',
            score=-2.5,
            percentile=75.0,
            metadata={'interpretation': 'moderate_yield'}
        )

        assert score_data['ticker'] == '005930'
        assert score_data['factor_name'] == 'Dividend_Yield'
        assert score_data['score'] == -2.5
        assert score_data['percentile'] == 75.0

        # Verify factor score was inserted
        query = """
            SELECT * FROM factor_scores
            WHERE ticker = %s AND region = %s AND factor_name = %s
        """
        result = postgres_test_db.execute_query(query, ('005930', 'KR', 'Dividend_Yield'))

        assert len(result) == 1
        assert float(result[0]['score']) == -2.5
        assert float(result[0]['percentile']) == 75.0

    def test_ohlcv_factory_single_day(self, ohlcv_factory, ticker_factory, postgres_test_db):
        """Test OHLCV factory with single day data"""

        # Create ticker first
        ticker_factory(ticker='005930')

        # Create single day OHLCV
        ohlcv_data = ohlcv_factory(
            ticker='005930',
            date='2024-03-29',
            base_price=75000,
            volume_base=10000000
        )

        assert len(ohlcv_data) == 1
        assert ohlcv_data[0]['ticker'] == '005930'
        assert ohlcv_data[0]['date'] == '2024-03-29'

        # Verify OHLCV was inserted
        query = "SELECT * FROM ohlcv_data WHERE ticker = %s AND region = %s AND date = %s"
        result = postgres_test_db.execute_query(query, ('005930', 'KR', '2024-03-29'))

        assert len(result) == 1
        assert result[0]['ticker'] == '005930'
        assert result[0]['volume'] > 0

    def test_ohlcv_factory_date_range(self, ohlcv_factory, ticker_factory, postgres_test_db):
        """Test OHLCV factory with date range"""

        # Create ticker first
        ticker_factory(ticker='005930')

        # Create date range OHLCV (Q1 2024)
        ohlcv_data = ohlcv_factory(
            ticker='005930',
            start_date='2024-01-01',
            end_date='2024-03-31',
            base_price=70000,
            volatility=0.02,
            volume_base=15000000
        )

        # Should have approximately 60-65 trading days (excluding weekends)
        assert len(ohlcv_data) >= 60
        assert len(ohlcv_data) <= 70

        # Verify OHLCV was inserted
        query = """
            SELECT COUNT(*) as count FROM ohlcv_data
            WHERE ticker = %s AND region = %s
              AND date >= %s AND date <= %s
        """
        result = postgres_test_db.execute_query(query, ('005930', 'KR', '2024-01-01', '2024-03-31'))

        assert result[0]['count'] == len(ohlcv_data)

    def test_complete_value_factor_test_data(self, ticker_factory, fundamentals_factory,
                                            factor_score_factory, ohlcv_factory, postgres_test_db):
        """Test creating complete test data for value factor integration tests"""

        # 1. Create ticker
        ticker_factory(
            ticker='000020',
            name='Test Corporation',
            sector='Finance',
            industry='Banking'
        )

        # 2. Create pykrx fundamentals (for Dividend Yield)
        fundamentals_factory(
            ticker='000020',
            date='2024-03-29',
            period_type='DAILY',
            data_source='pykrx',
            dividend_yield=3.5,
            per=12.0,
            pbr=0.8,
            market_cap=50000000000000
        )

        # 3. Create DART fundamentals (for EV/EBITDA)
        fundamentals_factory(
            ticker='000020',
            date='2024-03-31',
            fiscal_year=2024,
            period_type='SEMI-ANNUAL',
            data_source='DART',
            revenue=50000000000,
            ebitda=10000000000,
            total_assets=300000000000,
            total_liabilities=200000000000,
            current_assets=100000000000
        )

        # 4. Create factor scores
        factor_score_factory(
            ticker='000020',
            factor_name='Dividend_Yield',
            score=-3.0,
            percentile=80.0
        )

        factor_score_factory(
            ticker='000020',
            factor_name='EV_EBITDA',
            score=-2.0,
            percentile=70.0
        )

        # 5. Create OHLCV data (Q1 2024)
        ohlcv_factory(
            ticker='000020',
            start_date='2024-01-01',
            end_date='2024-03-31',
            base_price=15000,
            volatility=0.015
        )

        # Verify complete dataset
        query = "SELECT COUNT(*) as count FROM tickers WHERE ticker = %s"
        assert postgres_test_db.execute_query(query, ('000020',))[0]['count'] == 1

        query = "SELECT COUNT(*) as count FROM ticker_fundamentals WHERE ticker = %s"
        assert postgres_test_db.execute_query(query, ('000020',))[0]['count'] == 2

        query = "SELECT COUNT(*) as count FROM factor_scores WHERE ticker = %s"
        assert postgres_test_db.execute_query(query, ('000020',))[0]['count'] == 2

        query = "SELECT COUNT(*) as count FROM ohlcv_data WHERE ticker = %s"
        ohlcv_count = postgres_test_db.execute_query(query, ('000020',))[0]['count']
        assert ohlcv_count >= 60  # At least 60 trading days
