# Hong Kong Stock Exchange (HKEX) Trading Calendar
# Reference: https://www.hkex.com.hk/Services/Trading-hours-and-Severe-Weather-Arrangements

market: HK
exchanges: [HKEX]
timezone: Asia/Hong_Kong  # HKT (UTC+8)

# Regular trading hours
trading_hours:
  pre_market: null  # No pre-market
  regular:
    open: "09:30"
    lunch_break:
      start: "12:00"
      end: "13:00"
    close: "16:00"
  post_market: null  # No post-market
  note: "Continuous trading with 1-hour lunch break"

# HKEX holidays for 2025
# Source: HKEX official calendar
holidays_2025:
  - date: "2025-01-01"
    name: "New Year's Day"
    type: "public_holiday"

  - date: "2025-01-29"
    name: "Chinese New Year's Eve (half-day)"
    type: "early_close"
    close_time: "12:00"

  - date: "2025-01-30"
    name: "Chinese New Year (Day 1)"
    type: "public_holiday"

  - date: "2025-01-31"
    name: "Chinese New Year (Day 2)"
    type: "public_holiday"

  - date: "2025-02-03"
    name: "Chinese New Year (Day 4, replacement)"
    type: "public_holiday"

  - date: "2025-04-04"
    name: "Ching Ming Festival"
    type: "public_holiday"

  - date: "2025-04-18"
    name: "Good Friday"
    type: "public_holiday"

  - date: "2025-04-19"
    name: "Easter Saturday"
    type: "public_holiday"

  - date: "2025-04-21"
    name: "Easter Monday"
    type: "public_holiday"

  - date: "2025-05-01"
    name: "Labour Day"
    type: "public_holiday"

  - date: "2025-05-05"
    name: "Buddha's Birthday"
    type: "public_holiday"

  - date: "2025-05-31"
    name: "Tuen Ng Festival"
    type: "public_holiday"

  - date: "2025-07-01"
    name: "Hong Kong SAR Establishment Day"
    type: "public_holiday"

  - date: "2025-09-17"
    name: "Day After Mid-Autumn Festival"
    type: "public_holiday"

  - date: "2025-10-01"
    name: "National Day"
    type: "public_holiday"

  - date: "2025-10-11"
    name: "Chung Yeung Festival"
    type: "public_holiday"

  - date: "2025-12-25"
    name: "Christmas Day"
    type: "public_holiday"

  - date: "2025-12-26"
    name: "Boxing Day"
    type: "public_holiday"

# HKEX holidays for 2026
holidays_2026:
  - date: "2026-01-01"
    name: "New Year's Day"
    type: "public_holiday"

  - date: "2026-02-17"
    name: "Chinese New Year (Day 1)"
    type: "public_holiday"

  - date: "2026-02-18"
    name: "Chinese New Year (Day 2)"
    type: "public_holiday"

  - date: "2026-02-19"
    name: "Chinese New Year (Day 3)"
    type: "public_holiday"

  - date: "2026-04-05"
    name: "Ching Ming Festival"
    type: "public_holiday"

  - date: "2026-04-06"
    name: "Easter Monday (replacement)"
    type: "public_holiday"

  - date: "2026-04-10"
    name: "Good Friday"
    type: "public_holiday"

  - date: "2026-04-11"
    name: "Easter Saturday"
    type: "public_holiday"

  - date: "2026-05-01"
    name: "Labour Day"
    type: "public_holiday"

  - date: "2026-05-24"
    name: "Buddha's Birthday"
    type: "public_holiday"

  - date: "2026-06-19"
    name: "Tuen Ng Festival"
    type: "public_holiday"

  - date: "2026-07-01"
    name: "Hong Kong SAR Establishment Day"
    type: "public_holiday"

  - date: "2026-10-01"
    name: "National Day"
    type: "public_holiday"

  - date: "2026-10-06"
    name: "Day After Mid-Autumn Festival"
    type: "public_holiday"

  - date: "2026-10-21"
    name: "Chung Yeung Festival"
    type: "public_holiday"

  - date: "2026-12-25"
    name: "Christmas Day"
    type: "public_holiday"

  - date: "2026-12-26"
    name: "Boxing Day"
    type: "public_holiday"

# Early close days (half-day trading)
early_close_2025:
  - date: "2025-01-29"
    name: "Chinese New Year's Eve"
    close_time: "12:00"
    note: "Market closes at 12:00 noon"

  - date: "2025-12-24"
    name: "Christmas Eve"
    close_time: "12:00"
    note: "Market closes at 12:00 noon"

early_close_2026:
  - date: "2026-02-16"
    name: "Chinese New Year's Eve"
    close_time: "12:00"
    note: "Market closes at 12:00 noon"

  - date: "2026-12-24"
    name: "Christmas Eve"
    close_time: "12:00"
    note: "Market closes at 12:00 noon"

  - date: "2026-12-31"
    name: "New Year's Eve"
    close_time: "12:00"
    note: "Market closes at 12:00 noon"

# Notes
notes:
  - "HKEX trades Monday to Friday (except public holidays)"
  - "Trading hours: 09:30-12:00, 13:00-16:00 HKT"
  - "Lunch break: 12:00-13:00 (market closed)"
  - "Half-day trading (early close): Market closes at 12:00 noon"
  - "Typhoon signals (T8+) or black rainstorm warnings may suspend trading"
  - "Weekend holidays falling on weekday may have replacement holidays"
  - "For official calendar updates: https://www.hkex.com.hk"
